####################################
# NOTE:
####################################
# For the detailed information and usage of each configuration elements below, please check: https://espressifsystems.sharepoint.com/:x:/r/sites/Documentation/_layouts/15/Doc.aspx?sourcedoc=%7BC3634DD8-4F63-422B-805C-0CCDFABB42B0%7D&file=Configuration-Elements.xlsx&action=default&mobileredirect=true


####################################
# Shared Configuration
####################################

#syntax_version: version of this YMAL file. This configuration is shared by all documents in one project.
syntax_version: v0.62


######################################
# Document-specific Configuration
######################################

################################################
# Brief Introduction to Configuration Elements
################################################

# Document Basic Information

# document_name: the real name of your document, such as ESP32-C3 Series SoC Errata.

# document_path: the path from project path (./) to the document, such as ESP32-C3/ESP32-C3-Errata__EN.tex.

# published_document_filename: the filename used when the document is published on espressif.com, such as esp32-c3_errata_en.pdf. If the document is not intended to publish on espressif.com, put n/a here.

# chip_series: the chip series of the document, such as ESP32-C3.

# product_name: the product name of the document, such as ESP32-C3, ESP8684-WROOM-03. For chip product, the product_name may be same as the chip_series.

# document_type: the type of the document. The value can be chip datasheet, errata, hardware design guidelines, or technical reference manual.

# Document Status Information

# document_status: indicates the status of the document. The value can be: draft, in_review, or finalized.

# document_classification: indicates the target readers of the document. The value can be: confidential, restricted, or public.

# publish_status: indicates whether this document is ready for publishing or not. Two options: ready or not_ready.

# publish_location: indicates where the document will be released. Two options: internal_server or external_server.
  # If internal_server is set to true, then this document will be released on document preview Wiki page for developers: https://gitlab.example.cn/documentation/publish-overleaf-repos/-/wikis/document-preview
  # If internal_server is set to false, then this document will be released on document individual Wiki page for Documentation team, such as: https://gitlab.example.cn/documentation/publish-overleaf-repos/-/wikis/esp8684-module-datasheet
  # external_server option is reserved for future use.


# Document Template Information

# template_version: indicates what specific temple version the document is using.


documents:
########################################
# ESP32-P4 main__EN
########################################
    # Common configuration for internal release and public release
    - document_name: ESP32-P4 Technical Reference Manual
      doc_id: 7747 # Doc ID on CDP: 7747; Doc ID on espressif.com: 6895
      translation_docid: 7745 # Doc ID on CDP
      chip_series: ESP32-P4
      product_name:
        - ESP32-P4 SoC Series
      product_name_old_website:
        - ESP32-P4
      #soc_series_base_filter: # for software documents
      document_type: reference # or datasheet, reference, book, guide, application note
      document_type_old_website: reference
      document_type_label:
      document_status: in_progress
      version: v0.1
      language: en # or cn
      document_storage: cdp
      #document_link: n/a # for documents stored in cdp, then no need to provide document_link
      document_summary: The manual provides detailed and complete information on how to use the ESP32-P4 memory and peripherals.
      notify_subscribers: false # or true
      visibility_on_website: show # or hide
      schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
      # Configurations specific for internal release
      document_path: ESP32-P4/ESP32-P4-main__EN.tex
      published_document_filename: esp32-p4_technical_reference_manual_en.pdf
      document_classification: confidential
      publish_status:
        ready: false
        not_ready: true
      publish_location:
        internal_server: true
        external_server: false
      template_version: 1.2
########################################
# ESP32-P4 main__CN.tex
########################################
    # Common configuration for internal release and public release
    - document_name: ESP32-P4 技术参考手册
      doc_id: 7745 # Doc ID on CDP: 7745; Doc ID on espressif.com: 6897
      chip_series: ESP32-P4
      product_name:
        - ESP32-P4 SoC Series
      product_name_old_website:
        - ESP32-P4
      #soc_series_base_filter: # for software documents
      document_type: reference # or datasheet, reference, book, guide, application note
      document_type_old_website: reference
      document_type_label:
      document_status: in_progress
      version: v0.1
      language: cn # or en
      document_storage: cdp
      #document_link: n/a # for documents stored in cdp, then no need to provide document_link
      document_summary: 本手册提供了关于 ESP32-P4 的具体信息，包括各个功能模块的内部架构、功能描述和寄存器配置等。
      notify_subscribers: false # or true
      visibility_on_website: show # or hide
      schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
      # Configurations specific for internal release
      document_path: ESP32-P4/ESP32-P4-main__CN.tex
      published_document_filename: esp32-p4_technical_reference_manual_cn.pdf
      document_classification: confidential
      publish_status:
        ready: false
        not_ready: true
      publish_location:
        internal_server: true
        external_server: false
      template_version: 1.2
########################################
# ESP32-S3 main__EN
########################################
    # Common configuration for internal release and public release
    - document_name: ESP32-S3 Technical Reference Manual
      doc_id: 5421
      translation_docid: 5422
      chip_series: ESP32-S3
      product_name:
        - ESP32-S3 SoC Series
      product_name_old_website:
        - ESP32-S3
      #soc_series_base_filter: # for software documents
      document_type: reference # or datasheet, reference, book, guide, application note
      document_type_old_website: reference
      document_type_label:
      document_status: active
      version: v1.4
      language: en # or cn
      document_storage: cdp
      #document_link: n/a # for documents stored in cdp, then no need to provide document_link
      document_summary: The manual provides detailed and complete information on how to use the ESP32-S3 memory and peripherals.
      notify_subscribers: false # or true
      visibility_on_website: show # or hide
      schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
      #Configurations specific for public release
      document_path: ESP32-S3/ESP32-S3-main__EN.tex
      published_document_filename: esp32-s3_technical_reference_manual_en.pdf
      document_classification: public
      publish_status:
        ready: false
        not_ready: true
      publish_location:
        internal_server: false
        external_server: false
      template_version: 1.1.3
########################################
# ESP32-S3 main__CN.tex
########################################
    # Common configuration for internal release and public release
    - document_name: ESP32-S3 技术参考手册
      doc_id: 5422
      chip_series: ESP32-S3
      product_name:
        - ESP32-S3 SoC Series
      product_name_old_website:
        - ESP32-S3
      #soc_series_base_filter: # for software documents
      document_type: reference # or datasheet, reference, book, guide, application note
      document_type_old_website: reference
      document_type_label:
      document_status: active
      version: v1.4
      language: cn # or en
      document_storage: cdp
      #document_link: n/a # for documents stored in cdp, then no need to provide document_link
      document_summary: 本手册提供了关于 ESP32-S3 的具体信息，包括各个功能模块的内部架构、功能描述和寄存器配置等。
      notify_subscribers: false # or true
      visibility_on_website: show # or hide
      schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
      #Configurations specific for public release
      document_path: ESP32-S3/ESP32-S3-main__CN.tex
      published_document_filename: esp32-s3_technical_reference_manual_cn.pdf
      document_classification: public
      publish_status:
        ready: true
        not_ready: false
      publish_location:
        internal_server: false
        external_server: false
      template_version: 1.1.3
########################################
# ESP32-C5 main__EN
########################################
    # Common configuration for internal release and public release
    - document_name: ESP32-C5 Technical Reference Manual
      doc_id: 7743 # Doc ID on CDP: 7743; Doc ID on espressif.com: 7607
      translation_docid: 7741 # Doc ID on CDP
      chip_series: ESP32-C5
      product_name:
        - ESP32-C5 SoC Series
      product_name_old_website:
        - ESP32-C5
      #soc_series_base_filter: # for software documents
      document_type: reference # or datasheet, reference, book, guide, application note
      document_type_old_website: reference
      document_type_label:
      document_status: in_progress
      version: v0.1
      language: en # or cn
      document_storage: cdp
      #document_link: n/a # for documents stored in cdp, then no need to provide document_link
      document_summary: The manual provides detailed and complete information on how to use the ESP32-C5 memory and peripherals.
      notify_subscribers: false # or true
      visibility_on_website: show # or hide
      schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
      # Configurations specific for internal release
      document_path: ESP32-C5/ESP32-C5-main__EN.tex
      published_document_filename: esp32-c5_technical_reference_manual_en.pdf
      document_classification: confidential
      publish_status:
        ready: false
        not_ready: true
      publish_location:
        internal_server: true
        external_server: false
      template_version: 1.2
########################################
# ESP32-C5 main__CN.tex
########################################
    # Common configuration for internal release and public release
    - document_name: ESP32-C5 技术参考手册
      doc_id: 7741 # Doc ID on CDP: 7741; Doc ID on espressif.com: 7609
      chip_series: ESP32-C5
      product_name:
        - ESP32-C5 SoC Series
      product_name_old_website:
        - ESP32-C5
      #soc_series_base_filter: # for software documents
      document_type: reference # or datasheet, reference, book, guide, application note
      document_type_old_website: reference
      document_type_label:
      document_status: in_progress
      version: v0.1
      language: cn # or en
      document_storage: cdp
      #document_link: n/a # for documents stored in cdp, then no need to provide document_link
      document_summary: 本手册提供了关于 ESP32-C5 的具体信息，包括各个功能模块的内部架构、功能描述和寄存器配置等。
      notify_subscribers: false # or true
      visibility_on_website: show # or hide
      schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
      #Configurations specific for public release
      document_path: ESP32-C5/ESP32-C5-main__CN.tex
      published_document_filename: esp32-c5_technical_reference_manual_cn.pdf
      document_classification: confidential
      publish_status:
        ready: false
        not_ready: true
      publish_location:
        internal_server: true
        external_server: false
      template_version: 1.2
# ########################################
# # ESP32-C61 main__EN
# ########################################
#     # Common configuration for internal release and public release
#     - document_name: ESP32-C61/ESP32-C31 Technical Reference Manual
#       doc_id:
#       translation_docid:
#       chip_series: ESP32-C61
#       product_name:
#         - ESP32-C61 SoC Series
#       product_name_old_website:
#       #soc_series_base_filter: # for software documents
#       document_type: reference # or datasheet, reference, book, guide, application note
#       document_type_old_website: reference
#       document_type_label:
#       document_status: in_progress
#       version: v0.1
#       language: en # or cn
#       document_storage: cdp
#       #document_link: n/a # for documents stored in cdp, then no need to provide document_link
#       document_summary: The manual provides detailed and complete information on how to use the ESP32-C61/ESP32-C31 memory and peripherals.
#       notify_subscribers: false # or true
#       visibility_on_website: show # or hide
#       schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
#       # Configurations specific for internal release
#       document_path: ESP32-C61/ESP32-C61-main__EN.tex
#       published_document_filename: esp32-c61/esp32-c31_technical_reference_manual_en.pdf
#       document_classification: confidential
#       publish_status:
#         ready: false
#         not_ready: true
#       publish_location:
#         internal_server: true
#         external_server: false
#       template_version: 1.2
# ########################################
# # ESP32-C61 main__CN.tex
# ########################################
#     # Common configuration for internal release and public release
#     - document_name: ESP32-C61/ESP32-C31 技术参考手册
#       doc_id:
#       chip_series: ESP32-C61
#       product_name:
#         - ESP32-C61 SoC Series
#       product_name_old_website:
#       #soc_series_base_filter: # for software documents
#       document_type: reference # or datasheet, reference, book, guide, application note
#       document_type_old_website: reference
#       document_type_label:
#       document_status: in_progress
#       version: v0.1
#       language: cn # or en
#       document_storage: cdp
#       #document_link: n/a # for documents stored in cdp, then no need to provide document_link
#       document_summary: 本手册提供了关于 ESP32-C61/ESP32-C31 的具体信息，包括各个功能模块的内部架构、功能描述和寄存器配置等。
#       notify_subscribers: false # or true
#       visibility_on_website: show # or hide
#       schedule_release_date: # Any date in the future, format: 'MM/DD/YYYY  00:00:00 AM', or left empty for immediate release
#       #Configurations specific for public release
#       document_path: ESP32-C61/ESP32-C61-main__CN.tex
#       published_document_filename: esp32-c61/esp32-c31_technical_reference_manual_cn.pdf
#       document_classification: confidential
#       publish_status:
#         ready: false
#         not_ready: true
#       publish_location:
#         internal_server: true
#         external_server: false
#       template_version: 1.2
